# Generated by Django 5.1.6 on 2026-06-15 23:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActuacion',
            fields=[
                ('id_tipo_actuacion', models.AutoField(db_column='IdTipoActuacion', primary_key=True, serialize=False)),
                ('grupo', models.IntegerField(db_column='Grupo', default=0)),
                ('orden', models.PositiveSmallIntegerField(db_column='Orden', default=0)),
                ('breve', models.CharField(db_column='Breve', max_length=256)),
                ('amplio', models.TextField(blank=True, db_column='Amplio', default='', max_length=8192)),
                ('cierra', models.BooleanField(db_column='Cierra', default=False)),
            ],
            options={
                'verbose_name': 'Tipo de actuación',
                'verbose_name_plural': 'Tipos de actuación',
                'db_table': 'TipoActuaciones',
                'ordering': ['grupo', 'orden'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id_actuacion', models.AutoField(db_column='IdActuacion', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='FechaHora', default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('breve', models.CharField(db_column='Breve', max_length=256, verbose_name='Breve')),
                ('amplio', models.TextField(blank=True, db_column='Amplio', default='', max_length=8192, verbose_name='Amplio')),
                ('cierra', models.BooleanField(db_column='Cierra', default=False, verbose_name='Cierra')),
                ('id_user', models.ForeignKey(blank=True, db_column='IdUser', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_tipo_actuacion', models.ForeignKey(db_column='IdTipoActuacion', on_delete=django.db.models.deletion.PROTECT, to='seguridad.tipoactuacion', verbose_name='Tipo de actuación')),
            ],
            options={
                'verbose_name': 'Actuación',
                'verbose_name_plural': 'Actuaciones',
                'db_table': 'Actuaciones',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
    ]
