# Generated by Django 5.1.6 on 2026-06-15 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_tipoactuacion_actuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='id_mensaje',
            field=models.ForeignKey(blank=True, db_column='IdMensaje', null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.mensaje', verbose_name='Mensaje'),
        ),
    ]
