# Generated by Django 5.1.6 on 2026-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_actuacion_id_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuacion',
            name='id_mensaje',
        ),
        migrations.AddField(
            model_name='actuacion',
            name='mensaje',
            field=models.TextField(blank=True, db_column='Mensaje', null=True, verbose_name='ID del mensaje (InternetMessageId)'),
        ),
    ]
