# Generated by Django 5.1.6 on 2026-06-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_remove_actuacion_id_mensaje_actuacion_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionesAuto',
            fields=[
                ('IDAccAuto', models.AutoField(db_column='IDAccAuto', primary_key=True, serialize=False)),
                ('DescAccAuto', models.CharField(db_column='DescAccAuto', max_length=64, verbose_name='Descripción')),
                ('Tipo', models.CharField(choices=[('Mensaje', 'Mensaje'), ('Accion', 'Accion')], db_column='Tipo', max_length=16, verbose_name='Tipo')),
                ('Hijo', models.ForeignKey(blank=True, db_column='Hijo', help_text='IDAccAuto del registro hijo asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.accionesauto', verbose_name='Registro hijo')),
            ],
            options={
                'verbose_name': 'Acción automática',
                'verbose_name_plural': 'Acciones automáticas',
                'db_table': 'AccionesAuto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccAutoFields',
            fields=[
                ('IDAaccAutoField', models.AutoField(db_column='IDAaccAutoField', primary_key=True, serialize=False)),
                ('Orden', models.IntegerField(db_column='Orden', verbose_name='Orden')),
                ('Field', models.CharField(db_column='Field', max_length=128, verbose_name='Campo')),
                ('Cond', models.CharField(choices=[('EQ', 'Igual a'), ('NE', 'No igual a'), ('GT', 'Mayor que'), ('GE', 'Mayor o igual a'), ('LT', 'Menor que'), ('LE', 'Menor o igual que'), ('Contains', 'Contiene'), ('NContains', 'No contiene'), ('Like', 'Es como'), ('NLike', 'No es como'), ('Find', 'Aparece'), ('NFind', 'No aparece')], db_column='Cond', max_length=16, verbose_name='Condición')),
                ('Valor', models.CharField(db_column='Valor', max_length=256, verbose_name='Valor')),
                ('IDAccAuto', models.ForeignKey(db_column='IDAccAuto', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='seguridad.accionesauto', verbose_name='Acción automática')),
            ],
            options={
                'verbose_name': 'Campo de acción automática',
                'verbose_name_plural': 'Campos de acción automática',
                'db_table': 'AccAutoFields',
                'ordering': ['IDAccAuto', 'Orden'],
                'managed': True,
            },
        ),
    ]
