# Generated by Django 5.1.6 on 2026-06-21 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_actuacion_mensajes(apps, schema_editor):
    Actuacion = apps.get_model('seguridad', 'Actuacion')
    ActuacionMensaje = apps.get_model('seguridad', 'ActuacionMensaje')
    for act in Actuacion.objects.exclude(mensaje__isnull=True).exclude(mensaje=""):
        ActuacionMensaje.objects.create(
            actuacion=act,
            mensaje=act.mensaje,
            fecha_hora=act.fecha_hora,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_accionesauto_accautofields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuacionMensaje',
            fields=[
                ('id_actuacion_mensaje', models.AutoField(db_column='IdActuacionMensaje', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(db_column='Mensaje', verbose_name='Mensaje (InternetMessageId)')),
                ('fecha_hora', models.DateTimeField(db_column='FechaAplicacion', default=django.utils.timezone.now, verbose_name='Fecha de aplicación')),
                ('actuacion', models.ForeignKey(db_column='IdActuacion', on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='seguridad.actuacion')),
            ],
            options={
                'verbose_name': 'Aplicación de actuación',
                'verbose_name_plural': 'Aplicaciones de actuaciones',
                'db_table': 'ActuacionesMensajes',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
        migrations.RunPython(migrate_actuacion_mensajes),
        migrations.RemoveField(
            model_name='actuacion',
            name='mensaje',
        ),
    ]
